### ISSUE TITLE
`Quit (q)` does not work in paging

### ISSUE THREAD

**Issue by sabel83** [metashell/metashell#120]
It has the same effect as `Next page (RETURN)`

Update: it affects `#msh included headers` but works fine in MDB.

**Comment by r0mai** [comment]
It works for me:
```
| | | ` std::__1::allocator<char> at /Users/r0mai/workspace/metashell/bin/app/metashell/../include/metashell
| | |   /libcxx/memory:1706:29 (Memoization from /Users/r0mai/workspace/metashell/bin/app/metashell/../inclu
| | |   de/metashell/libcxx/memory:995:22)
Next page (RETURN), Show all (a), Quit (q): q
(mdb)
```

**Comment by r0mai** [comment]
Can you debug this function? https://github.com/metashell/metashell/blob/master/lib/core/stdout_console.cpp#L33

Maybe there is something funky going on in your terminal.

**Comment by sabel83** [comment]
I've done further testing: it works in mdb for me as well but does not work in `#msh included headers`, so I must be using the paging code wrong in that pragma.

**Comment by r0mai** [comment]
You should check the return value of `pager::new_line()`, and terminate if it return false.
