### ISSUE TITLE
Assertion failed 

### ISSUE THREAD

**Issue by DkatoNaB** [metashell/metashell#130]
**OP System: Linux mint**
 - Linux 4.4.0-21-generic # 37-Ubuntu SMP apr 18 2016
 - x86_64 GNU/Linux

**Case:**
- Running test_metashell_definition_succeeds_when_cwd_is_not_writable
  - Assertion failed
  - Test case: test_metashell_definition_succeeds_when_cwd_is_not_writable
  - Location: $USER/MetaShell/metashell-master/test/system/app/core/test_cwd.cpp:123

**Comment by sabel83** [comment]
Hi,

What is the git commit id? `test/system/app/core/test_cwd.cpp` on the `master` branch has only 110 lines.

**Comment by sabel83** [comment]
I've built the current head of `master` on Linux Mint 18 (kde, 64-bit). The code compiled and all tests passed.
