### ISSUE TITLE
Metashell misses system includes on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by etam** [metashell/metashell#131]
I'm using:
metashell 8e4cf6f
openSUSE Tumbleweed
gcc 6.1.1
clang 3.8.0

I've build metashell using provided scripts (./install_build_dependencies.sh && ./build.sh)

What I've got:

    $ metashell
    > #include <vector>
    <stdin>:1:10: fatal error: 'vector' file not found
    #include <vector>
             ^
    1 error generated.
    
    > #msh sysincludes
    /tmp/just-VvTNev/shell
    /usr/bin/../include/metashell/templight
    /usr/local/include
    /usr/include
    
    $ templight_metashell -E -x c++ - -v < /dev/null
    clang version 3.8.0 (tags/RELEASE_380/final)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin
    clang -cc1 version 3.8.0 based upon LLVM 3.8.0 default target x86_64-unknown-linux-gnu
    ignoring nonexistent directory "/usr/bin/../lib/clang/3.8.0/include"
    ignoring nonexistent directory "/include"
    #include "..." search starts here:
    #include <...> search starts here:
     /usr/local/include
     /usr/include
    End of search list.
    # 1 "<stdin>"
    # 1 "<built-in>" 1
    # 1 "<built-in>" 3
    # 325 "<built-in>" 3
    # 1 "<command line>" 1
    # 1 "<built-in>" 2
    # 1 "<stdin>" 2
    
    $ clang++ -E -x c++ - -v < /dev/null
    clang version 3.8.0 (tags/RELEASE_380/final 262553)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin
    Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-suse-linux/6
    Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/6
    Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-suse-linux/6
    Candidate multilib: .;@m64
    Selected multilib: .;@m64
     "/usr/bin/clang-3.8" -cc1 -triple x86_64-unknown-linux-gnu -E -disable-free -disable-llvm-verifier -main-file-name - -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /usr/bin/../lib64/clang/3.8.0 -internal-isystem /usr/bin/../lib64/gcc/x86_64-suse-linux/6/../../../../include/c++/6 -internal-isystem /usr/bin/../lib64/gcc/x86_64-suse-linux/6/../../../../include/c++/6/x86_64-suse-linux -internal-isystem /usr/bin/../lib64/gcc/x86_64-suse-linux/6/../../../../include/c++/6/backward -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib64/clang/3.8.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/etam -ferror-limit 19 -fmessage-length 271 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
    clang -cc1 version 3.8.0 based upon LLVM 3.8.0 default target x86_64-unknown-linux-gnu
    ignoring nonexistent directory "/include"
    #include "..." search starts here:
    #include <...> search starts here:
     /usr/bin/../lib64/gcc/x86_64-suse-linux/6/../../../../include/c++/6
     /usr/bin/../lib64/gcc/x86_64-suse-linux/6/../../../../include/c++/6/x86_64-suse-linux
     /usr/bin/../lib64/gcc/x86_64-suse-linux/6/../../../../include/c++/6/backward
     /usr/local/include
     /usr/bin/../lib64/clang/3.8.0/include
     /usr/include
    End of search list.
    # 1 "<stdin>"
    # 1 "<built-in>" 1
    # 1 "<built-in>" 3
    # 325 "<built-in>" 3
    # 1 "<command line>" 1
    # 1 "<built-in>" 2
    # 1 "<stdin>" 2

**Comment by sabel83** [comment]
Thank you for the bug report. I have updated `build.sh` to make Templight use gcc's include path. Please try the current head of `master` and let me know if this works for you.

Note that if you have already built Templight and/or Metashell, you should delete the `3rd/templight/build` and `bin` directories before re-running `build.sh`.

**Comment by etam** [comment]
That works. Thanks!
