### ISSUE TITLE
build system does not recognize openSUSE Tumbleweed

### ISSUE THREAD

**Issue by etam** [metashell/metashell#145]
in openSUSE Tumbleweed /etc/SuSE-release was earlier deprecated and now removed. /etc/os-release should be used instead.

Currently its contents are

    NAME="openSUSE Tumbleweed"
    # VERSION="20161003"
    ID=opensuse
    ID_LIKE="suse"
    VERSION_ID="20161003"
    PRETTY_NAME="openSUSE Tumbleweed"
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:opensuse:tumbleweed:20161003"
    BUG_REPORT_URL="https://bugs.opensuse.org"
    HOME_URL="https://www.opensuse.org/"

**Comment by r0mai** [comment]
Thanks for the report. It would be very appreciated if you could open a pull request with a fix for this.

You'll most likely need to modify this part of the code:
https://github.com/metashell/metashell/blob/master/tools/detect_platform.sh#L24-L26

**Comment by sabel83** [comment]
Thank you for the bug report. I've fixed it.

**Comment by etam** [comment]
Unfortunately this also needs fixes: https://github.com/metashell/metashell/blob/master/cmake/Modules/Platform.cmake#L34

**Comment by sabel83** [comment]
I have fixed that as well.
