### ISSUE TITLE
termcap library detection broken

### ISSUE THREAD

**Issue by jonesmz** [metashell/metashell#150]
I needed to implement these changes before cmake would locate my termcap library:
```
diff --git a/cmake/Modules/FindTermcap.cmake b/cmake/Modules/FindTermcap.cmake
index 2f63dae..9c08943 100644
--- a/cmake/Modules/FindTermcap.cmake
+++ b/cmake/Modules/FindTermcap.cmake
@@ -36,14 +36,14 @@ endif()

 # Open SuSE
 if (CMAKE_SIZEOF_VOID_P EQUAL 8)
-  set(TERMCAP_LIBRARYDIR "${TERMCAP_LIBRARYDIR};/usr/lib64/termcap")
+  set(TERMCAP_LIBRARYDIR "${TERMCAP_LIBRARYDIR};/usr/lib64/")
 else()
-  set(TERMCAP_LIBRARYDIR "${TERMCAP_LIBRARYDIR};/usr/lib/termcap")
+  set(TERMCAP_LIBRARYDIR "${TERMCAP_LIBRARYDIR};/usr/lib/")
 endif()

@@ -55,7 +55,7 @@ find_path(
 )
 find_library(
   TERMCAP_LIBRARY
-  NAMES termcap
+  NAMES libtermcap.so.2
   HINTS ${TERMCAP_LIBRARYDIR}
 )
```

This is with the Gentoo distribution, with the sys-libs/libtermcap-compat-2.0.8-r3 package installed

**Comment by r0mai** [comment]
I think with these changes other platforms could break, but it should be possible to search for termcap under both directories with both names.

**Comment by jonesmz** [comment]
I don't see how other platforms could possibly work without the

 find_library(
   TERMCAP_LIBRARY
-  NAMES termcap
+  NAMES libtermcap.so.2
   HINTS ${TERMCAP_LIBRARYDIR}
 )

change

Even putting libtermcap.so wasn't enough, cmake explicitly needed me to provide libtermcap.so.2



Possibly other platforms are defining the find_library function differently?

**Comment by sabel83** [comment]
I have added Gentoo support to the build scripts (`install_build_dependencies.sh`, `build.sh`) and updated the CMake scripts following your suggestions. Please let me know if this fixes your issues.

**Comment by jonesmz** [comment]
Problem solved with latest git master. Thanks!
