### ISSUE TITLE
How do I use std::cout?

### ISSUE THREAD

**Issue by weegreenblobbie** [metashell/metashell#159]
How do I use std::cout?

I'm trying 2.1.0 on Ubuntu 14.04 and expected this to work:

    $ metashell
    > #include <iostream>
    > std::cout << "hello\n";

But I get the following error:

    <stdin>:1:6: fatal error: no type named 'cout' in namespace 'std'

**Comment by sabel83** [comment]
The code you are about to run here is runtime C++ code. Metashell can't execute that, it can display the result of expressions evaluating to a type. For example you can ask Metashell what the type of that expression is:

```cpp
$ metashell
> #include <iostream>
> decltype(std::cout << "hello\n")
std::basic_ostream<char> &
```

**Comment by weegreenblobbie** [comment]
Thanks for the clarification. :+1:
