### ISSUE TITLE
Spelling error on website

### ISSUE THREAD

**Issue by Tarirah** [metashell/metashell#161]
Hello,
I believe there is a spelling error in the macro example for enabling the preprocessor here:
https://metashell.readthedocs.io/en/latest/manual/getting_started/index.html
At "testing macros", it says the command would be `#msh perprocessor mode`, which is either pretty irritating or should be `#msh preprocessor mode`

**Comment by r0mai** [comment]
Thanks for the report, it has been fixed on master, but the changes not yet propagated to the website.

@sabel83: the readthedocs project is still pointing to your, sabel83 fork as the source. Can you update it to this one?

**Comment by sabel83** [comment]
I've updated the readthedocs project.

**Comment by r0mai** [comment]
Thanks! Looks good now, the change is visible on the website.
