### ISSUE TITLE
fibnoacci example error on ubuntu with package metashell

### ISSUE THREAD

**Issue by cppljevans** [metashell/metashell#166]
On my system:

      evansl@lje-OptiPlex-9020:~/prog_dev/metashell$ uname -a
    Linux lje-OptiPlex-9020 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    evansl@lje-OptiPlex-9020:~/prog_dev/metashell$ 

after metashell 3.0.0 was installed with synaptic, running the fibnoacci example from:

  [http://metashell.org/manual/getting_started/index.html#how-about-fibonacci](url)

resulted in an error at the `(mdb) step 3` command:

    evansl@lje-OptiPlex-9020:~/prog_dev/metashell$ make metashell
    metashell --console=readline -- -std=c++14 
    /*
     * Template metaprogramming shell 3.0.0
     * 
     * Metashell Copyright (C) 2015 Abel Sinkovics (abel@sinkovics.hu)
     *                              Andras Kucsma  (andras.kucsma@gmail.com)
     * This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain
     * conditions; for details visit <http://www.gnu.org/licenses/>.
     * 
     * Based on
     *   Boost.Wave 2.3.2.5400 [linux/GNU C++ version 5.4.0 20160609]
     *   Readline   6.3
     * 
     * Using precompiled headers
     * Maximum template depth: 0
     * 
     * Getting help: #msh help
     */
    
    > #include "fib.hpp"
    > #include <boost/mpl/int.hpp>
    > boost::mpl::int_<fib<6>::value>
    mpl_::int_<13>
    > #include <metashell/scalar.hpp>
    > SCALAR(fib<6>::value)
    std::integral_constant<int, 13>
    > #msh mdb int_<fib<6>::value>
    For help, type "help".
    Metaprogram started
    (mdb) step 3
    Metaprogram finished
    <stdin>:2:26: fatal error: use of undeclared identifier 'int_'; did you mean 'int'?
    ::metashell::impl::wrap< int_<fib<6>::value> > __metashell_v;
                             ^~~~
                             int
    1 error generated.
    
    (mdb)

**Comment by r0mai** [comment]
I believe it should be `#msh mdb boost::mpl::int_<fib<6>::value>`

**Comment by r0mai** [comment]
Actually there should be a `using namespace boost::mpl;` in your `fib.hpp` if you followed

**Comment by cppljevans** [comment]
Many thanks r0mai.  That solved problem.
