### ISSUE TITLE
metashell --console=json fails

### ISSUE THREAD

**Issue by cppljevans** [metashell/metashell#168]
On a ubuntu 16.04 LTS system, this occurs:

    evansl@lje-OptiPlex-9020:~/prog_dev/metashell$ metashell --help|grep -A 4 -e '--console arg'
      --console arg (=readline) Console type. Possible values: plain, readline, 
                                json
      --nosplash                Disable the splash messages
      --log arg                 Log into a file. When it is set to -, it logs into 
                                the console.
    evansl@lje-OptiPlex-9020:~/prog_dev/metashell$ metashell --console=readline
    /*
     * Template metaprogramming shell 3.0.0
     * 
     * Metashell Copyright (C) 2015 Abel Sinkovics (abel@sinkovics.hu)
     *                              Andras Kucsma  (andras.kucsma@gmail.com)
     * This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under
     * certain conditions; for details visit <http://www.gnu.org/licenses/>.
     * 
     * Based on
     *   Boost.Wave 2.3.2.5400 [linux/GNU C++ version 5.4.0 20160609]
     *   Readline   6.3
     * 
     * Using precompiled headers
     * Maximum template depth: 0
     * 
     * Getting help: #msh help
     */
    
    > #msh quit
    
    evansl@lje-OptiPlex-9020:~/prog_dev/metashell$ metashell --console=json
    {"type":"comment","paragraphs":[{"first_line_indentation":"","rest_of_lines_indentation":"","content":"Template metaprogramming shell 3.0.0"},{"first_line_indentation":"","rest_of_lines_indentation":"","content":""},{"first_line_indentation":"","rest_of_lines_indentation":"","content":"Metashell Copyright (C) 2015 Abel Sinkovics (abel@sinkovics.hu)"},{"first_line_indentation":"","rest_of_lines_indentation":"","content":"                             Andras Kucsma  (andras.kucsma@gmail.com)"},{"first_line_indentation":"","rest_of_lines_indentation":"","content":"This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions; for details visit <http://www.gnu.org/licenses/>."},{"first_line_indentation":"","rest_of_lines_indentation":"","content":""},{"first_line_indentation":"","rest_of_lines_indentation":"","content":"Based on"},{"first_line_indentation":"  Boost.Wave ","rest_of_lines_indentation":"             ","content":"2.3.2.5400 [linux/GNU C++ version 5.4.0 20160609]"},{"first_line_indentation":"  Readline   ","rest_of_lines_indentation":"             ","content":"6.3"},{"first_line_indentation":"","rest_of_lines_indentation":"","content":""},{"first_line_indentation":"","rest_of_lines_indentation":"","content":"Using precompiled headers"},{"first_line_indentation":"","rest_of_lines_indentation":"","content":"Maximum template depth: 0"},{"first_line_indentation":"","rest_of_lines_indentation":"","content":""},{"first_line_indentation":"","rest_of_lines_indentation":"","content":"Getting help: #msh help"}]}
    {"type":"prompt","prompt":">"}
    Killed
    evansl@lje-OptiPlex-9020:~/prog_dev/metashell$ 

The metashell process had to be killed with the system monitor app :(

**Comment by r0mai** [comment]
You can exit either by entering the right, json formatted command corresponding to `#msh quit`, or using Ctrl+D.

**Comment by r0mai** [comment]
But this interface was not designed to be used from the command line by a user. It's supposed to make metashell usable by other programs by communicating using stdin/stdout using a documented, machine readable json format.

**Comment by cppljevans** [comment]
Ah!  Thanks for the clarification.  The `metashell --help` output gave no hint that it was not to be used
from the command line.  Only by looking at:

[http://metashell.org/manual/embedding/index.html#embedding-metashell-into-other-applications](url)

would the user have any clue that it should not be used from the command line, but even
that was unclear.

**Comment by r0mai** [comment]
From http://metashell.org/manual/embedding/index.html#embedding-metashell-into-other-applications
>  The format of the commands and the output will be structured JSON documents separated by \n characters.

in other words, the input json has to be formatted into a single line

**Comment by cppljevans** [comment]
OK.  That wasn't obvious from the docs.
