### ISSUE TITLE
How much of metashell's functionality is available if built with Visual Studio 2017 v15.5.4?

### ISSUE THREAD

**Issue by juandent** [metashell/metashell#179]
Hi,

Tihs Github project does not appear to be portable to Visual Studio. Before attempting to build it with Visual Studio 2017 v15.5.4, has anyone had experience trying to build metashell with this compiler?

To what degree does it have all the functionality compared to the online metashell?

Regards,
Juan Dent

**Comment by r0mai** [comment]
You can build metashell on Windows by following the steps on this page: http://metashell.org/getting_metashell/build/index.html

The online Metashell demo is built from the master branch of this repository, it should have the same functionality as the one you build locally from master. Of course you can include local files in your local build.

**Comment by juandent** [comment]
Hi @r0mai ,
I git cloned this project and tried running build.bat as directed in the index.html, but it does not compile correctly with Visual Studio 2017 -- it says it cannot find the MSbuild tools for v141 (VS 2017)

Any ideas?

Regards
Juan

**Comment by r0mai** [comment]
This article suggests, that this might not be a metashell related problem: https://developercommunity.visualstudio.com/content/problem/4849/msbuild-cannot-find-the-v141-toolset.html

Unfortunately I don't have easy access to VS2017 at the moment. Please let us know if you find out something.

**Comment by r0mai** [comment]
You could also try to compile metashell with VS2015 (v14.0). That is known to work.

**Comment by sabel83** [comment]
The head of `master` can be built with v14.15. The Appveyor jobs use that version as well.
