### ISSUE TITLE
C++17 Support

### ISSUE THREAD

**Issue by schmidh** [metashell/metashell#189]
Are there any plans to support C++17 (Clang 5) in the future?

**Comment by sabel83** [comment]
The master branch uses a parched Clang 5.0.1 as the Templighg binary.

**Comment by schmidh** [comment]
I think the CLANG version in _install_build_dependencies.sh_ should be _5.0.1_ for Ubuntu installations. At least this worked for me. But I'm not sure as the failed build was on another box of mine and I do not fully understand the build process.

**Comment by sabel83** [comment]
That specifies the version of ˋclang_formatˋ we use to format the code. The version of Clang we base the Templight binary on depends on which version of Clang we have in the ˋ3rd/templightˋ directory of the source tree.
