### ISSUE TITLE
Including other 3rd Party Libraries

### ISSUE THREAD

**Issue by schmidh** [metashell/metashell#200]
Sorry for having a general question. I'm not quite sure what can be done with Metashell and what it's limitations are. The examples are mostly based on Boost.MPL and there are already formatter headers available out-of-the-box.

Would it be possible to use other libraries too or can I use only the headers that are in the 3rd party directory? Can I even use all the headers that are in the 3rd party folder?

Let's say I want to play around with Boost.HANA or Brigand, would that be a viable thing to do with Metashell? Would I need to write my own formatter headers in this case?

Kind regards!

**Comment by sabel83** [comment]
If you are using a local Metashell (build it from source or use the binary installer), you can provide the include path to the shell. If those libraries are available on the include path, you will be able to use them. You need to write your own formatters.

Note that the 3rd party directory contains code used to compile Metashell itself. Those are not the headers available by default inside Metashell.

**Comment by schmidh** [comment]
Ok, got it. Thanks for clarification!
