### ISSUE TITLE
Compilation Failure on Fedora 28 x86_64 due to linker errors

### ISSUE THREAD

**Issue by jnbrq** [metashell/metashell#207]
I am trying to compile metashell on Fedora 28. I got the latest sources from github. I followed the build guidelines. And the error is the following: (in the final step)

```
/usr/bin/ld: ../../3rd/termcap/src/libtermcap_lib.a(termcap.c.o)(.text+0x38f): unresolvable R_X86_64_PC32 relocation against symbol `ospeed'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

How can I resolve this issue?

**Comment by sabel83** [comment]
Thank you for the bug report. I could reproduce it and I've applied a workaround for it on the `master` branch. Please use the latest commit there and in case it does not work for you, let us know.
