### ISSUE TITLE
Not working with bear

### ISSUE THREAD

**Issue by Cons-Cat** [metashell/metashell#270]
When I generate `compile_commands.json` using [bear](https://github.com/rizsotto/Bear), and run `metashell --load_compile_commands ./compile_commands.json`, I get an error saying: `JSON parsing failed: Lists are expected as top level elements only`. As far as I can tell, the JSON that bear produces looks well formed. It begins and ends with a `[` / `]`, and generally looks the same to me as what CMake produces. There don't seem to be any issues yet about what to do after this error.

**Comment by sabel83** [comment]
Hi, thank you for reporting it. Metashell has only been tested with CMake's compilation database, which is using the `"command"` element. `bear` seems to use `"arguments"` instead (see https://clang.llvm.org/docs/JSONCompilationDatabase.html for examples). As a workaround until Metashell gets fixed, you might try updating the generated compilation database.

**Comment by sabel83** [comment]
A fix for this has now been merged.
