### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by iMichka** [metashell/metashell#282]
Hello.

I am a maintainer of Homebrew.
We are trying to build methashell on macOS Ventura, and hit some issues.

See:
https://github.com/Homebrew/homebrew-core/pull/128202

I was able to build methashell locally from the latest commit.
Would it be possible to tag a new release so we can update the package on our side?
Thanks

**Comment by sabel83** [comment]
Hi, I'm in the process of upgrading all dependencies, which I expect to take a few weeks. I'll tag a new release once I'm done.

**Comment by sabel83** [comment]
I've created `v5.0.0`.

**Comment by iMichka** [comment]
Thanks! We are updating it here: https://github.com/Homebrew/homebrew-core/pull/138798
